name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia
  workflow_dispatch: # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: Lucas-Alves-Paula
          outputs: |
            output/github-contribution-grid-snake.svg
